{% set name = "arcjetCV" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/magnus-haw/arcjetCV/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 68c324f224a054b4a995b81291df6242666269a63da538a8b8c4075fc89776f9

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - pip
    - setuptools
    - python
    - numpy
    - qt-main
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pytorch
    - pyside6
    - opencv
    - matplotlib-base
    - pandas
    - pyarrow
    - scikit-learn
    - segmentation-models-pytorch
    - torchvision
    - ocl-icd-system

test:
  imports:
    - arcjetCV
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/magnus-haw/arcjetCV/
  summary: 'App to process arcjet videos and segment the edge of the shock and of the sample.'
  description: |
    App to process arcjet videos and segment the edge of the shock and of the sample.

  license: NASA-1.3
  license_file: LICENSE
  doc_url: https://arcjetcv.readthedocs.io/
  dev_url: https://github.com/magnus-haw/arcjetCV/

extra:
  recipe-maintainers:
    - fsemerar
